FROM oven/bun
WORKDIR /app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./bun.lock ./bun.lock
COPY ./packages  ./packages
COPY ./apps/backend ./apps/backend
RUN bun install
RUN bun run prisma:generate
EXPOSE 5000
CMD ["bun", "run", "--cwd", "apps/backend", "index.ts"]